# Generated by Django 4.0.5 on 2022-07-04 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_aouth2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
